name: vtt-innovation
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.11
  
  # Core data processing
  - pandas>=1.5.0
  - numpy>=1.22.0
  
  # Data modeling and validation
  - pydantic>=1.10.0
  
  # Progress bars
  - tqdm>=4.65.0
  
  # Visualization
  - matplotlib>=3.6.0
  - networkx>=3.0
  - seaborn>=0.12.0
  - plotly>=5.0.0
  - kaleido
  
  # Machine learning and clustering
  - scikit-learn>=1.2.0
  - hdbscan
  
  # Development tools
  - jupyter>=1.0.0
  - notebook>=6.5.0
  
  # Configuration utilities
  - toml
  - python-dotenv
  - pillow
  
  # Package manager
  - pip>=23.0
  
  # Packages installed via pip (not available in conda or better from pip)
  - pip:
    # LangChain ecosystem
    - langchain
    - langchain-core
    - langchain-community
    - langchain-openai>=0.0.1
    
    # OpenAI and Azure integration
    - openai>=1.0.0
    - azure-search-documents
    - azure-identity
    
    # Streamlit web app framework
    - streamlit 